CREATE TABLE document_type_templates (
  document_type document_type NOT NULL PRIMARY KEY,
  required_sections JSONB NOT NULL,
  default_stub_plan JSONB NOT NULL
);

INSERT INTO document_type_templates VALUES
('annual_report',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"VD-ord / Executive Summary","required":true,"semantic_role":"executive_summary"},
   {"module_type":"kpi_grid","label":"Nyckeltal","required":true},
   {"module_type":"financial_summary","label":"Finansiell sammanfattning","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"VD-ord","semantic_role":"executive_summary","content":"","data":{},"stub":true},
   {"order":3,"module_type":"kpi_grid","title":"Nyckeltal","data":{"kpis":[]},"stub":true},
   {"order":4,"module_type":"financial_summary","title":"Finansiell sammanfattning","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('quarterly',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"kpi_grid","label":"Nyckeltal","required":true},
   {"module_type":"financial_summary","label":"Finansiell sammanfattning","required":true},
   {"module_type":"text_spread","label":"Utsikt/Outlook","required":true,"semantic_role":"outlook"},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"kpi_grid","title":"Nyckeltal","data":{"kpis":[]},"stub":true},
   {"order":3,"module_type":"financial_summary","title":"Finansiell sammanfattning","data":{},"stub":true},
   {"order":4,"module_type":"text_spread","title":"Utsikt","semantic_role":"outlook","content":"","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('pitch',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('proposal',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]');
