-- Add more document types to the enum
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'sustainability_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'board_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'investor_update';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'case_study';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'white_paper';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'sales_proposal';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'project_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'brand_guide';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'product_sheet';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'newsletter';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'event_program';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'company_profile';

-- Seed templates for new types (if document_type_templates exists)
INSERT INTO document_type_templates VALUES
('sustainability_report',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"VD-ord / Inledning","required":true,"semantic_role":"executive_summary"},
   {"module_type":"kpi_grid","label":"Hållbarhetsnyckeltal","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"VD-ord","semantic_role":"executive_summary","content":"","data":{},"stub":true},
   {"order":3,"module_type":"kpi_grid","title":"Hållbarhetsnyckeltal","data":{"kpis":[]},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('board_report',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Sammanfattning","required":true,"semantic_role":"executive_summary"},
   {"module_type":"table","label":"Beslutspunkter","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},
   {"order":3,"module_type":"table","title":"Beslutspunkter","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('investor_update',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"kpi_grid","label":"Nyckeltal","required":true},
   {"module_type":"financial_summary","label":"Finansiell utveckling","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"kpi_grid","title":"Nyckeltal","data":{"kpis":[]},"stub":true},
   {"order":3,"module_type":"financial_summary","title":"Finansiell utveckling","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('case_study',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Utmaning","required":true,"semantic_role":"challenge"},
   {"module_type":"text_spread","label":"Lösning","required":true,"semantic_role":"solution"},
   {"module_type":"kpi_grid","label":"Resultat","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Utmaning","semantic_role":"challenge","content":"","data":{},"stub":true},
   {"order":3,"module_type":"text_spread","title":"Lösning","semantic_role":"solution","content":"","data":{},"stub":true},
   {"order":4,"module_type":"kpi_grid","title":"Resultat","data":{"kpis":[]},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('white_paper',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Sammanfattning","required":true,"semantic_role":"executive_summary"},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('sales_proposal',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Erbjudande","required":true,"semantic_role":"offer"},
   {"module_type":"table","label":"Prissättning","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Erbjudande","semantic_role":"offer","content":"","data":{},"stub":true},
   {"order":3,"module_type":"table","title":"Prissättning","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('project_report',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Projektsammanfattning","required":true,"semantic_role":"executive_summary"},
   {"module_type":"kpi_grid","label":"Projektmilstolpar","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Projektsammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},
   {"order":3,"module_type":"kpi_grid","title":"Milstolpar","data":{"kpis":[]},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('brand_guide',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Varumärkesintroduktion","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Vårt varumärke","content":"","data":{},"stub":true},
   {"order":3,"module_type":"text_spread","title":"Logotyp & Användning","content":"","data":{},"stub":true},
   {"order":4,"module_type":"text_spread","title":"Färgpalett","content":"","data":{},"stub":true},
   {"order":5,"module_type":"text_spread","title":"Typografi","content":"","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('product_sheet',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Produktöversikt","content":"","data":{},"stub":true},
   {"order":3,"module_type":"kpi_grid","title":"Specifikationer","data":{"kpis":[]},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('newsletter',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('event_program',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"table","label":"Program/Schema","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"table","title":"Program","data":{},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'),
('company_profile',
 '[{"module_type":"cover","label":"Omslag","required":true},
   {"module_type":"text_spread","label":"Om oss","required":true},
   {"module_type":"kpi_grid","label":"Nyckeltal","required":true},
   {"module_type":"back_cover","label":"Baksida","required":true}]',
 '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},
   {"order":2,"module_type":"text_spread","title":"Om oss","content":"","data":{},"stub":true},
   {"order":3,"module_type":"kpi_grid","title":"Nyckeltal","data":{"kpis":[]},"stub":true},
   {"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]')
ON CONFLICT (document_type) DO NOTHING;
