-- Migration 032: refined doctype templates (haiku-pass 2026-05-05).
--
-- Replaces every row in document_type_templates with the haiku-pass
-- output. Each doctype now carries:
--   - richer required_sections + default_stub_plan (purpose-fit, not
--     generic cover+body+back_cover)
--   - recommended_pages (page-budget hint, e.g. '1-2', '8-12')
--   - tone_hints (single-sentence stylistic stance for design-language)
--   - disclosures (formal info-blocks the doctype mandates, JSONB array)
--
-- The smyra-core plan-structure + design-language steps read these new
-- fields via api.getStubPlan and inject them into Claude's prompts.

-- Ensure all doctype enum values exist (some are new since the haiku
-- pass — ceo_letter, compliance_report, competitive_analysis etc. were
-- carried in setup.ts but never reflected in the enum).
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'annual_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'board_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'brand_guide';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'case_study';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ceo_letter';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'company_profile';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'competitive_analysis';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'compliance_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'custom';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'event_program';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'impact_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'internal_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'investor_update';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'market_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'monthly_update';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'newsletter';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'onboarding_guide';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'pitch';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'press_release';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'process_doc';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'product_sheet';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'project_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'proposal';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'quarterly';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'research_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'sales_proposal';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'strategy_doc';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'sustainability_report';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'training_material';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'white_paper';

-- Add the three new columns. Backward-compatible (nullable).
ALTER TABLE document_type_templates
  ADD COLUMN IF NOT EXISTS recommended_pages TEXT,
  ADD COLUMN IF NOT EXISTS tone_hints TEXT,
  ADD COLUMN IF NOT EXISTS disclosures JSONB DEFAULT '[]'::jsonb;

-- Wipe and re-seed all rows from the haiku-pass output. Safe — table
-- is purely a catalog (no FKs, no user data). Anything missing falls
-- back to FALLBACK_TEMPLATES in document-type-templates.js.
DELETE FROM document_type_templates;

-- annual_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('annual_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Titelomslag för årsrapporten med företagslogotyp, år och huvudtema."},{"module_type":"text_spread","label":"VD-ord","required":true,"semantic_role":"executive_summary","description":"VD-brev eller ordskörd för året. Narrativ ton, ofta med personlig signering och ansiktsbild."},{"module_type":"kpi_grid","label":"Nyckeltal - Finansiell överblick","required":true,"semantic_role":null,"description":"5-8 övergripande nyckeltal för året (omsättning, resultat, lönsamhet, avkastning, medarbetarantal)."},{"module_type":"text_spread","label":"Året i korthet","required":false,"semantic_role":null,"description":"Sammanfattning av väsentliga händelser, strategiska satsningar och milstolpar under året."},{"module_type":"text_spread","label":"Affärsverksamhet & strategi","required":false,"semantic_role":null,"description":"Beskrivning av verksamhetsområden, marknadspositioning, strategiska riktlinjer och långsiktiga mål."},{"module_type":"text_spread","label":"Hållbarhet & ESG","required":false,"semantic_role":null,"description":"Miljömässig och social påverkan, hållbarhetsmål, väsentliga ESG-nyckeltal och insatser."},{"module_type":"text_spread","label":"Risk & osäkerhet","required":false,"semantic_role":null,"description":"Väsentliga risker för verksamheten, riskhanttering och identifierade osäkerhetsfaktorer för framtiden."},{"module_type":"financial_summary","label":"Finansiell utveckling","required":true,"semantic_role":null,"description":"Detaljerade finansiella tabeller (resultaträkning, balansräkning, kassaflöde) med jämförelsetal från föregående år."},{"module_type":"text_spread","label":"Styrelseberättelse & Styrning","required":false,"semantic_role":null,"description":"Styrelsens organisation, löner, bolagsstyrning, interna kontroller och revisionsfunktion."},{"module_type":"text_spread","label":"Revisorsrapport","required":false,"semantic_role":null,"description":"Extern revisors yttrande över årsredovisningen, väsentliga revisionsfynd och attestering."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Kontaktuppgifter, företagsinformation och läsarvägledning."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"VD-ord","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Nyckeltal","semantic_role":null,"data":{"kpis":[]},"stub":true},{"order":4,"module_type":"text_spread","title":"Året i korthet","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Affärsverksamhet & strategi","semantic_role":null,"content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Hållbarhet & ESG","semantic_role":null,"content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Risk & osäkerhet","semantic_role":null,"content":"","data":{},"stub":true},{"order":8,"module_type":"financial_summary","title":"Finansiell utveckling","semantic_role":null,"data":{},"stub":true},{"order":9,"module_type":"text_spread","title":"Styrelseberättelse & Styrning","semantic_role":null,"content":"","data":{},"stub":true},{"order":10,"module_type":"text_spread","title":"Revisorsrapport","semantic_role":null,"content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '20-40',
   'Formell och omfattande: årlig redovisning för alla intressenter (investerare, revisorer, personal, leverantörer). Balans mellan tydlig datafokus och narrativ genomgång. Inte marknadsföring.',
   '["Styrelsens organisering och löner","Viktiga händelser efter årsbokslutsdatum","Närstående transaktioner","Väsentliga redovisningsprinciper","Revisorsyttrande","Bolagsstyrningsrapport"]'::jsonb);

-- board_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('board_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Titelomslag med möte/datum och sammanfattning av dagordningens huvudsakliga punkt(er)."},{"module_type":"text_spread","label":"Dagordning & Sammanfattning","required":true,"semantic_role":"executive_summary","description":"Kortfattad sammanfattning av ärenden som ska hanteras under mötet med rekommendationer från ledning."},{"module_type":"kpi_grid","label":"Nyckeltal & Verksamhetsstatus","required":true,"semantic_role":null,"description":"Aktuella KPI:er, status för större projekt och väsentliga varningar eller risker som kräver styrelsebeslut."},{"module_type":"table","label":"Beslutspunkter & Rekommendationer","required":true,"semantic_role":null,"description":"Strukturerad tabell med ärende, bakgrund, risker och rekommendation för styrelsen. Möjliggör snabb beslutsfattning."},{"module_type":"text_spread","label":"Detaljerad analys per ärendet","required":false,"semantic_role":null,"description":"Fördjupad analys av något större beslutsärende med bakgrund, alternativ och konsekvenser."},{"module_type":"text_spread","label":"Risker & Compliance","required":false,"semantic_role":null,"description":"Väsentliga risker för verksamheten, regelefterlevnad, interna kontroller och revisionsfynd som styrelsem måste granska."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Referensmaterial, kontaktuppgifter, mötesdatum och instruktioner för sekretesskydd."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Dagordning & Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Status & Nyckeltal","semantic_role":null,"data":{"kpis":[]},"stub":true},{"order":4,"module_type":"table","title":"Beslutspunkter","semantic_role":null,"data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Detaljerad analys","semantic_role":null,"content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Risker & Compliance","semantic_role":null,"content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '4-6',
   'Formell beslutsunderlag. Fokus på väsentliga risker, rekommendationer och säkerhet. Kort och saklig utan omväxling.',
   '["Sekretesspolicy för styrelsehandlingar","Väsentliga risker och hot","Compliance & regelefterlevnad","Revisorsfynd och åtgärder","Närstående transaktioner över tröskelvärde"]'::jsonb);

-- brand_guide
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('brand_guide',
   '[{"module_type":"cover","label":"Omslag","required":true,"description":"Hero cover — varumärkesnamn och visuell identitet"},{"module_type":"text_spread","label":"Varumärkesintroduktion","required":true,"semantic_role":"brand_intro","description":"Varumärkespromise, essens och värden — vad vi står för"},{"module_type":"text_spread","label":"Logotyp och användning","required":true,"semantic_role":"logo_system","description":"Logotyp, minimalt avstånd, negativ form, varianter och användarfall"},{"module_type":"text_spread","label":"Färgpalett","required":true,"semantic_role":"color_palette","description":"Primärfärger, sekundärfärger, accentfärger med hex-koder och användningsregler"},{"module_type":"text_spread","label":"Typografi","required":true,"semantic_role":"typography","description":"Typsnitt för rubrik och brödtext, storlekar, vikt och radavstånd — körexempel"},{"module_type":"text_spread","label":"Röst och ton","required":false,"semantic_role":"voice_tone","description":"Språklig stil, ordval, ton för olika sammanhang — från formell till ledig"},{"module_type":"text_spread","label":"Visuell stil och motiv","required":false,"semantic_role":"visual_motifs","description":"Bildstil, ikoner, former, mönster och designelement som karakteriserar märket"},{"module_type":"text_spread","label":"Praktiska exemplar","required":false,"semantic_role":"usage_examples","description":"Verkliga tillämpningar på brevpapper, visitkort, digital webb, sociala medier"},{"module_type":"back_cover","label":"Baksida","required":true,"description":"Baksida med kontakt till brand-teamet"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Varumärkesintroduktion","semantic_role":"brand_intro","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Logotyp och användning","semantic_role":"logo_system","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Färgpalett","semantic_role":"color_palette","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Typografi","semantic_role":"typography","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Röst och ton","semantic_role":"voice_tone","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Visuell stil och motiv","semantic_role":"visual_motifs","content":"","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Praktiska exemplar","semantic_role":"usage_examples","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '12-20',
   'Auktoritativ men tillgänglig — tydlig, strukturerad vägledning för konsekvent tillämpning med fokus på visuella exemplar och praktiska regler',
   '[]'::jsonb);

-- case_study
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('case_study',
   '[{"module_type":"cover","label":"Omslag — Kundfall","required":true,"description":"Titelblad med kundlogotyp och case-tema"},{"module_type":"text_spread","label":"Kundens Utmaning","required":true,"semantic_role":"challenge","description":"Detaljerad bakgrund till kundproblemet, affärskontext, smärtpunkt"},{"module_type":"text_spread","label":"Vår Lösning","required":true,"semantic_role":"solution","description":"Hur vi löste problemet, implementeringsmetod, timeline"},{"module_type":"kpi_grid","label":"Resultat & Metriker","required":true,"semantic_role":"results","description":"Före/efter-tal, ROI, effektivitetsökning, kostnadsbesparingar"},{"module_type":"text_spread","label":"Kundens Feedback","required":false,"semantic_role":"testimonial","description":"Citat från kundledning, nöjdhet, rekommendation"},{"module_type":"back_cover","label":"Baksida","required":true,"description":"Kontaktuppgifter, länk till mer information"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Kundfall","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Utmaning","semantic_role":"challenge","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Lösning","semantic_role":"solution","content":"","data":{},"stub":true},{"order":4,"module_type":"kpi_grid","title":"Resultat","semantic_role":"results","data":{"kpis":[]},"stub":true},{"order":5,"module_type":"text_spread","title":"Kundens Åsikt","semantic_role":"testimonial","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '4-6',
   'Berättande och konkret. Fokus på mätbar påverkan och kundöversättande, inte försäljar-prat.',
   '[]'::jsonb);

-- ceo_letter
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('ceo_letter',
   '[{"module_type":"text_spread","label":"Brev","required":true,"semantic_role":"ceo_letter_body","description":"VD:s personliga brev med hero-öppning, kärnmeddelande och undertecknad underskrift"}]'::jsonb,
   '[{"order":1,"module_type":"text_spread","title":"VD-brev","semantic_role":"ceo_letter_body","content":"","data":{},"stub":true}]'::jsonb,
   '1-2',
   'Personlig och auktoritet — VD:s egen röst med tankeledande perspektiv, optimism och hänsyn till mottagarnas intressen',
   '[]'::jsonb);

-- company_profile
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('company_profile',
   '[{"module_type":"cover","label":"Omslag","required":true,"description":"Hero cover med företagsnamn, logotyp och kort tagline"},{"module_type":"text_spread","label":"Om oss","required":true,"semantic_role":"company_intro","description":"Kort introduktion av företaget, historia, mission och värderingar"},{"module_type":"kpi_grid","label":"Nyckeltal","required":true,"description":"Visningstall för storlek, marknadspresens, resultat — 4-6 KPI:er"},{"module_type":"text_spread","label":"Vårt ledarskap","required":false,"semantic_role":"leadership","description":"Kort presentation av ledningsgruppen med namn, titlar och fokusområden"},{"module_type":"text_spread","label":"Kontakt & möjligheter","required":false,"semantic_role":"contact","description":"Kontaktuppgifter för försäljning, partnerskap och media"},{"module_type":"back_cover","label":"Baksida","required":true,"description":"Baksida med kontakt eller QR-kod"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Om oss","semantic_role":"company_intro","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Nyckeltal","data":{"kpis":[]},"stub":true},{"order":4,"module_type":"text_spread","title":"Vårt ledarskap","semantic_role":"leadership","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Kontakt & möjligheter","semantic_role":"contact","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '4-6',
   'Professionell men välkomnande — etablerad kredibilitet blandad med mänsklig värme och tillgänglighet för kunder och partners',
   '[]'::jsonb);

-- competitive_analysis
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('competitive_analysis',
   '[{"module_type":"cover","label":"Omslag","required":true},{"module_type":"text_spread","label":"Marknadsöversikt","required":true,"semantic_role":"market_context","description":"Marknadens struktur, huvudaktörer och konkurrensintensitet."},{"module_type":"table","label":"Konkurrentjämförelse","required":true,"semantic_role":"comparison_matrix","description":"Strukturerad jämförelse av produkter, prissättning, funktioner och positionering."},{"module_type":"text_spread","label":"SWOT per konkurrent","required":true,"semantic_role":"competitor_swot","description":"Enskilda analyser av styrkor, svagheter, möjligheter och hot för nyckelaktörer."},{"module_type":"text_spread","label":"Vår positionering","required":true,"semantic_role":"our_positioning","description":"Vår position i landskapet, differentierare och konkurrensfördelar."},{"module_type":"back_cover","label":"Baksida","required":true}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Marknadsöversikt","semantic_role":"market_context","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Konkurrensintensitet & barriärer","content":"","data":{},"stub":true},{"order":4,"module_type":"table","title":"Konkurrentjämförelse","semantic_role":"comparison_matrix","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Konkurrent 1 - SWOT","semantic_role":"competitor_swot","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Konkurrent 2 - SWOT","semantic_role":"competitor_swot","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Konkurrent 3 - SWOT","semantic_role":"competitor_swot","content":"","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Positioneringskarta & strategi","semantic_role":"our_positioning","content":"","data":{},"stub":true},{"order":9,"module_type":"text_spread","title":"Vår differentiering","content":"","data":{},"stub":true},{"order":10,"module_type":"text_spread","title":"Rekommendationer & nästa steg","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '8-12',
   'Objektiv, strukturerad, insiktsfull — fokuserar på relative fördelar och marknadspositioning.',
   '["Informationskällor och datainsamlingsperiod","Marknadsdefiniering och konkurrenturval","Begränsningar i jämförelsedata och tillgänglig information","Antaganden om produktkategorisering och funktionalitet"]'::jsonb);

-- compliance_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('compliance_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":"cover"},{"module_type":"text_spread","label":"Sammanfattning & Resultat","required":true,"semantic_role":"executive_summary","description":"Överensstämmelsestatus, kritiska fynd, övergripande riskprofil, ledningens intyg"},{"module_type":"text_spread","label":"Regelverk & Ramverk","required":true,"semantic_role":"regulatory_framework","description":"Tillämpliga lagar, standarder, direktiv (MiFID II, GDPR, Solvens II, ISO, etc.)"},{"module_type":"table","label":"Kontrollmatris","required":true,"semantic_role":"control_matrix","description":"Regel/kontroll ID, beskrivning, ansvarig, test-resultat (Pass/Fail), risknivå"},{"module_type":"text_spread","label":"Risk-bedömning","required":false,"semantic_role":"risk_assessment","description":"Identifierade risker, sannolikhet, påverkeffekt, befintliga åtgärder, residuell risk"},{"module_type":"table","label":"Risk-Register","required":false,"semantic_role":"risk_register","description":"Risk ID, beskrivning, kategori, ägare, sannolikhet × påverkeffekt, åtgärdsstatus"},{"module_type":"text_spread","label":"Åtgärdsplan","required":false,"semantic_role":"action_plan","description":"Fynd från granskning, åtgärd, tidsplan, ansvarig, status (öppen/stängd), deadline"},{"module_type":"table","label":"Gransknings- & Certifieringsresultat","required":false,"semantic_role":"audit_results","description":"Revisor/utförare, datum, omfattning, konklusion, reservation om tillämplig, nästa granskning"},{"module_type":"text_spread","label":"Handlingsplan & Framtida Fokus","required":false,"semantic_role":"future_outlook","description":"Prioriterade förbättringsområden, tidslinje för implementering, ansvar"},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":"back_cover"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Sammanfattning & Resultat","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Regelverk & Ramverk","semantic_role":"regulatory_framework","content":"","data":{},"stub":true},{"order":4,"module_type":"table","title":"Kontrollmatris","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Riskbedömning","semantic_role":"risk_assessment","content":"","data":{},"stub":true},{"order":6,"module_type":"table","title":"Risk-Register","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Åtgärdsplan","semantic_role":"action_plan","content":"","data":{},"stub":true},{"order":8,"module_type":"table","title":"Granskningsresultat","data":{},"stub":true},{"order":9,"module_type":"text_spread","title":"Framtida Fokus","semantic_role":"future_outlook","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '12-20',
   'Formell, saklig, auditerad transparens med fokus på riskkontroll och regelefterlevnad',
   '["Tidsperiod för granskning & rapportering","Revisor/granskande organs namn och oberoendeerklärelse","Konvention för riskklassificering (t.ex. kritisk/högt/medel/lågt)","Definition av ''kontroll'' och status-klassificering (Pass/Fail/Delvis)","Ledningens intyg om att granskningsprocessen är lämplig","Bekräftelse på efterlevnad av tillämpliga standards"]'::jsonb);

-- custom
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('custom',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Dokumentets titel, datummarkering och företagsidentitet."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Kontaktuppgifter och relevanta footer-uppgifter."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '4-6',
   'Neutral och flexibel — anpassningsbar till användarens eget syfte utan tvingande struktur.',
   '[]'::jsonb);

-- event_program
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('event_program',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Eventnamn, datum, plats och huvudtema/tagline."},{"module_type":"text_spread","label":"Eventoversikt","required":true,"semantic_role":"executive_summary","description":"Kort introduktion till event — syfte, målgrupp, väntade resultat och höjdpunkter."},{"module_type":"table","label":"Dagsprogram / Schema per dag","required":true,"semantic_role":null,"description":"Dag-för-dag tidstabell med tider, sessioner, pauserna och spåren (om flera)."},{"module_type":"table","label":"Talarlista & sessioner","required":false,"semantic_role":null,"description":"Talare, deras titel, session-abstrakt och tid för presentation."},{"module_type":"text_spread","label":"Praktisk information","required":true,"semantic_role":null,"description":"Plats och instruktioner, parkering, logistik, Wi-Fi och kontaktuppgifter on-site."},{"module_type":"text_spread","label":"Nätverkning & social program","required":false,"semantic_role":null,"description":"Mötesplatser, middag, reception, workshop och andra sociala aktiviteter."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Sponsor/partner information och uppföljningsdetaljer (efter-event feedback)."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Eventoversikt","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"table","title":"Dagsprogram","semantic_role":null,"data":{},"stub":true},{"order":4,"module_type":"table","title":"Talarlista & sessioner","semantic_role":null,"data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Praktisk information","semantic_role":null,"content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Nätverkning & social program","semantic_role":null,"content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '4-6',
   'Inspirerad och välorganiserad — praktisk men engagerande presentation av agenda och kontakt.',
   '["Datum, tid och väderlek varning (om relevant)","Aksessibilitet och covid-anpassningar (om relevant)"]'::jsonb);

-- impact_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('impact_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":"cover"},{"module_type":"text_spread","label":"Inledning & Mission","required":true,"semantic_role":"executive_summary","description":"Uppdrag, målgrupp, teori om förändring (Theory of Change), långsiktiga syften"},{"module_type":"text_spread","label":"Impact Theory of Change","required":true,"semantic_role":"theory_of_change","description":"Visualiserad process från aktiviteter över output till outcome & impact; antaganden"},{"module_type":"kpi_grid","label":"Outcome & Impact-Nyckeltal","required":true,"semantic_role":"impact_metrics","description":"Antal begåvnade, antal hushåll lyfta från fattigdom, kWh sparade, häckningsframgång"},{"module_type":"text_spread","label":"Representativ Berättelse","required":false,"semantic_role":"beneficiary_story","description":"Konkret exempel från målgrupp — före/efter, personlig röst, mätbar ändring"},{"module_type":"text_spread","label":"Metodologi & Attribution","required":false,"semantic_role":"attribution_method","description":"Hur vi mäter impact, kontrollgrupp om tillämpbar, datakällor, begränsningar"},{"module_type":"table","label":"Målgrupp-Data","required":false,"semantic_role":"beneficiary_analysis","description":"Demografi, geografisk spridning, könsfördelning, sektor, klassificering av behov"},{"module_type":"text_spread","label":"Lärdommar & Nästa Steg","required":false,"semantic_role":"learnings","description":"Vad vi lärt oss, framgångsfaktorer, utmaningar, skalningsplaner"},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":"back_cover"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Inledning & Uppdrag","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Impact Theory of Change","semantic_role":"theory_of_change","content":"","data":{},"stub":true},{"order":4,"module_type":"kpi_grid","title":"Impact-Nyckeltal","data":{"kpis":[]},"stub":true},{"order":5,"module_type":"text_spread","title":"Berättelse från Målgrupp","semantic_role":"beneficiary_story","content":"","data":{},"stub":true},{"order":6,"module_type":"table","title":"Målgrupp-Demografi","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Metodologi & Mätning","semantic_role":"attribution_method","content":"","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Lärdommar & Skalning","semantic_role":"learnings","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '12-20',
   'Autentisk, mål-fokuserad narrativ som visar konkret människor förändring genom rigorös mätning',
   '["Definition av outcome vs impact","Datasource & granskningsmässighet för måluppfyllelse","Attribution-metodologi — kontrollgrupp, jämförbara kohorter, eller antagande-analys","Potentiella mätfördomar och risker","Målgruppens samtycke & etik"]'::jsonb);

-- internal_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('internal_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":"cover"},{"module_type":"text_spread","label":"Sammanfattning & Rekommendation","required":true,"semantic_role":"executive_summary","description":"Frågeställning, huvudfynd, rekommendation, beslutsalternativ för ledningen"},{"module_type":"text_spread","label":"Problemformulering","required":false,"semantic_role":"problem_statement","description":"Bakgrund, nuläge, varför det är viktigt, tidshorisont, scope"},{"module_type":"text_spread","label":"Analys & Fynd","required":true,"semantic_role":"analysis","description":"Djupgående analys med data, logik, alternativ-utredning, styrkor & svagheter"},{"module_type":"table","label":"Jämförelsetabell / Alternativ-analys","required":false,"semantic_role":"options_comparison","description":"Alternativ A/B/C jämfört på kostnad, tidsplan, risk, slutresultat"},{"module_type":"kpi_grid","label":"Nyckelmetri & Påverkan","required":false,"semantic_role":"impact_metrics","description":"Finansiell påverkan, ROI, tidsperspektiv, andra KPI för olika beslut"},{"module_type":"text_spread","label":"Rekommendation & Implementation","required":true,"semantic_role":"recommendation","description":"Föreslagen väg framåt, implementeringssteg, ansvarig, tidslinje, riskmitigering"},{"module_type":"text_spread","label":"Risker & Antaganden","required":false,"semantic_role":"risk_assumptions","description":"Kritiska antaganden, potentiella fallgropar, osäkerhet, beroenden"},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":"back_cover"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Sammanfattning & Rekommendation","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Problemformulering","semantic_role":"problem_statement","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Analys & Fynd","semantic_role":"analysis","content":"","data":{},"stub":true},{"order":5,"module_type":"table","title":"Alternativ-jämförelse","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Rekommendation","semantic_role":"recommendation","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Risker & Antaganden","semantic_role":"risk_assumptions","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '8-12',
   'Analytisk, objektiv, fokuserad på faktabakgrundat beslutsfattande med transparent logik',
   '["Tidspunkt för rapportens framtagning","Relevanta antaganden & datakällor","Beslutskriteria (budget, tid, risk-tolerans)","Tidshorizon för rekommendationen"]'::jsonb);

-- investor_update
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('investor_update',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Titelomslag med uppdateringsperiod och huvudfokus (t.ex. ''Investeraruppdatering Q3 2024'')."},{"module_type":"text_spread","label":"Höjdpunkter & Executive Summary","required":true,"semantic_role":"executive_summary","description":"Kortfattad överblick av perioden med viktigaste affärshändelser, strategiska framsteg och framtidsutsikter."},{"module_type":"kpi_grid","label":"Finansiella nyckeltal","required":true,"semantic_role":null,"description":"5-7 viktigaste KPI:er för investerare (omsättning, EBITDA, kassaflöde, EPS, skuld/EBITDA, ROE). Trendsökande layout."},{"module_type":"text_spread","label":"Grafsektion - Finansiell prestanda","required":true,"semantic_role":null,"description":"Diagram för omsättning, EBITDA-utveckling och kassaflöde. Visar trend och vinstsamhet. Data-driven utan företagsbroschyr-känsla."},{"module_type":"financial_summary","label":"Finansiell sammanfattning","required":true,"semantic_role":null,"description":"Resultaträkning, balansräkning och kassaflödesanalys med jämförelser från tidigare perioder. Konsekvent format."},{"module_type":"text_spread","label":"Marknads- & segmentanalys","required":false,"semantic_role":null,"description":"Verksamhetsöversikt per affärsområde/geografi med tillväxt, marginaler och strategiska fokusområden."},{"module_type":"text_spread","label":"Outlook & strategi","required":false,"semantic_role":"outlook","description":"Framtidsutsikter, strategiska initiativ, tillväxtdrivkrafter och väsentliga risker för kommande period."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Investerarkontakt, disclaimer, datakällor och definitioner av användbara nyckeltal."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Höjdpunkter","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Finansiella nyckeltal","semantic_role":null,"data":{"kpis":[]},"stub":true},{"order":4,"module_type":"text_spread","title":"Finansiell prestanda","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"financial_summary","title":"Finansiella rapporter","semantic_role":null,"data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Affärsöversikt & strategi","semantic_role":null,"content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Outlook","semantic_role":"outlook","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '8-12',
   'Investerar-fokuserad finansiell rapport. Kredibel och transparent utan mjuk säljpitch. Data överskuggar bilder.',
   '["Forward-looking statements disclaimer","Definition av icke-IFRS mått (t.ex. EBITDA-justerad)","Väsentliga risker för framtida resultat","Väsentliga händelser efter rapportperioden"]'::jsonb);

-- market_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('market_report',
   '[{"module_type":"cover","label":"Omslag","required":true},{"module_type":"text_spread","label":"Sammanfattning","required":true,"semantic_role":"executive_summary","description":"Huvudsakliga marknadsinsikter, storlek, tillväxttakt och nyckelmegatrender."},{"module_type":"kpi_grid","label":"Marknadssiffror (TAM/SAM/SOM)","required":true,"semantic_role":"market_sizing","description":"Totalt adresserbar marknad, servicebar marknad och vår servicebar marknad."},{"module_type":"text_spread","label":"Marknadssegment & trender","required":true,"semantic_role":"segmentation_trends","description":"Indelning av marknaden, tillväxtdrivkrafter och framväxande trender."},{"module_type":"table","label":"Konkurrenslandskap","required":true,"semantic_role":"competitive_landscape","description":"Huvudaktörer, marknadsandelar och positionering."},{"module_type":"back_cover","label":"Baksida","required":true}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Marknadsstorlek & tillväxt","semantic_role":"market_sizing","data":{"kpis":[]},"stub":true},{"order":4,"module_type":"text_spread","title":"Marknadssegment","semantic_role":"segmentation_trends","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Trender & drivkrafter","content":"","data":{},"stub":true},{"order":6,"module_type":"table","title":"Konkurrenter & marknadsandelar","semantic_role":"competitive_landscape","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Möjligheter & hot","content":"","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Framtidsutsikter & rekommendationer","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '12-20',
   'Analytisk, datadrivet, handlingsbar — fokusererar på marknadsmöjligheter och strategiska implikationer.',
   '["Datakällor och undersökningsmetod","Tidsperiod för data (historik, prognos)","Antaganden om marknadsdefinition och segmentering","Disclaimer om framtidsprognos"]'::jsonb);

-- monthly_update
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('monthly_update',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Titelomslag med månad, år och eventuell sammanfattning av huvudtema eller fokus."},{"module_type":"kpi_grid","label":"Aktuella nyckeltal","required":true,"semantic_role":null,"description":"3-6 viktigaste månadskPI:er för snabb överblick (omsättning, orderingång, likviditet, kundnöjdhet, sjukfrånvaro)."},{"module_type":"text_spread","label":"Highlights & affärshändelser","required":true,"semantic_role":null,"description":"Viktigaste händelserna under månaden presenterat som bullets. Snabb läsning för ledning och medarbetare."},{"module_type":"text_spread","label":"Utmaningar & risker","required":false,"semantic_role":null,"description":"Identifierade utmaningar, flaskhalsar eller problem som påverkar verksamheten denna månad."},{"module_type":"text_spread","label":"Fokus för nästa månad","required":true,"semantic_role":null,"description":"Planerade aktiviteter, milstolpar och prioriteringar för kommande månad. Skapa fokus och förväntniner."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Snabb referens: viktiga datum, kommande möten, kontaktuppgifter."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"kpi_grid","title":"Nyckeltal","semantic_role":null,"data":{"kpis":[]},"stub":true},{"order":3,"module_type":"text_spread","title":"Highlights & affärshändelser","semantic_role":null,"content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Utmaningar & risker","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Fokus nästa månad","semantic_role":null,"content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '4-6',
   'Koncis och handlingsorienterad. Internt kommunikationsmedel för snabb statusöversikt. Fokus på åtgärder nästa period.',
   '[]'::jsonb);

-- newsletter
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('newsletter',
   '[{"module_type":"cover","label":"Omslag","required":true,"description":"Tidskrift-liknande omslag med utgåva/månad, huvudrubrik och upphetsande visuell teaser"},{"module_type":"text_spread","label":"Huvudstory/Spotlight","required":true,"semantic_role":"featured_story","description":"En större, featured artikel eller nyheter med rubrik och introduktionsbild"},{"module_type":"text_spread","label":"Korta nyheter","required":false,"semantic_role":"news_briefs","description":"2-4 kortare nyheter, uppdateringar eller highlights i bullet-format"},{"module_type":"text_spread","label":"Kommande event/Kalender","required":false,"semantic_role":"calendar_events","description":"Framtida event, webinar eller viktiga datum för läsarna"},{"module_type":"text_spread","label":"Call to Action","required":false,"semantic_role":"cta_section","description":"Uppmaning för läsare — länka till mer info, registrera dig, kontakta oss"},{"module_type":"back_cover","label":"Baksida","required":true,"description":"Baksida med unsubscribe, sociala medier och kontakt"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Huvudstory","semantic_role":"featured_story","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Korta nyheter","semantic_role":"news_briefs","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Kommande event","semantic_role":"calendar_events","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Vad gör vi härnäst","semantic_role":"cta_section","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '1-2',
   'Vänlig och engagerande — uppdaterad information paketerad för snabb läsning med fokus på läsarnas intresse och framtida möjligheter',
   '["Avprenumeration / unsubscribe-länk","GDPR/dataskyddsinfo — hur vi använder e-postadressen"]'::jsonb);

-- onboarding_guide
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('onboarding_guide',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Välkomstkort med företagslogotyp, titel och mottagares namn."},{"module_type":"text_spread","label":"Välkommen","required":true,"semantic_role":"executive_summary","description":"Introduktion från chefen eller HR. Varmt välkomna-meddelande och förväntningar för första veckorna."},{"module_type":"text_spread","label":"Vår kultur & värderingar","required":true,"semantic_role":null,"description":"Företagets kärnvärden, kultur och arbetssätt presenterade på ett engagerande sätt."},{"module_type":"text_spread","label":"Verktyg & IT-miljö","required":false,"semantic_role":null,"description":"Lista över IT-verktyg, lösenordshantering, access och teknisk setup."},{"module_type":"table","label":"100-dagars plan","required":true,"semantic_role":null,"description":"Strukturerad tidslinje för vecka 1, månad 1 och månad 3 med milstolpar och fokusområden."},{"module_type":"text_spread","label":"Kontakter & organisationsöversikt","required":false,"semantic_role":null,"description":"Checklista med nyckelkontakter, team-email, slack-kanaler och organisationsstruktur."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Kontaktinformation, support och fler resurser."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Välkommen!","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Vår kultur & värderingar","semantic_role":null,"content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Verktyg & IT-miljö","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"table","title":"100-dagars plan","semantic_role":null,"data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Nyckelkontakter","semantic_role":null,"content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '8-12',
   'Varmhöll och uppmuntrande — välkomnande atmosfär med praktisk vägledning.',
   '[]'::jsonb);

-- pitch
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('pitch',
   '[{"module_type":"cover","label":"Omslag — Investerarpitch","required":true,"description":"Titelblad med hero-bild, company name, pitch-tema"},{"module_type":"text_spread","label":"Problem","required":true,"semantic_role":"challenge","description":"Marknadsproblem eller smärtpunkt som löses"},{"module_type":"kpi_grid","label":"Marknadsstorlek & Potentiell","required":true,"semantic_role":"market_size","description":"TAM, SAM, SOM, marknadstillväxt i procent"},{"module_type":"text_spread","label":"Lösning","required":true,"semantic_role":"solution","description":"Vad ni gör, unik värdeproposition, differentierare"},{"module_type":"kpi_grid","label":"Traction & KPI:er","required":true,"semantic_role":"traction","description":"Aktiva kunder, ARR/MRR-tillväxt, retention, viktiga milstolpar"},{"module_type":"text_spread","label":"Affärsmodell","required":false,"semantic_role":"business_model","description":"Intäktsmöjligheter, marginaler, upsell-strategi"},{"module_type":"text_spread","label":"Teamet","required":true,"semantic_role":"team","description":"Grundare & ledningsgrupp — erfarenhet, tidigare framgångar"},{"module_type":"text_spread","label":"Finansieringsöverenskommelse","required":true,"semantic_role":"ask","description":"Beloppet som söks, användning av medel, värdebedömning"},{"module_type":"back_cover","label":"Baksida — Kontakt","required":true,"description":"Kontaktuppgifter, webbplats, sociala medier"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Pitch Deck","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Problem","semantic_role":"challenge","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Marknadsstorlek","semantic_role":"market_size","data":{"kpis":[]},"stub":true},{"order":4,"module_type":"text_spread","title":"Lösning","semantic_role":"solution","content":"","data":{},"stub":true},{"order":5,"module_type":"kpi_grid","title":"Traction","semantic_role":"traction","data":{"kpis":[]},"stub":true},{"order":6,"module_type":"text_spread","title":"Teamet","semantic_role":"team","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Finansieringsöverenskommelse","semantic_role":"ask","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Kontakt","data":{},"stub":true}]'::jsonb,
   '8-12',
   'Självsäker, ambitionerad, fakta-drivet — no fluff. Investerare vill se klara tal och exit-vägar.',
   '[]'::jsonb);

-- press_release
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('press_release',
   '[{"module_type":"cover","label":"Omslag","required":true,"description":"Pressmeddelande-omslag med datum och plats (dateline)"},{"module_type":"text_spread","label":"Pressmeddelande","required":true,"semantic_role":"press_body","description":"Rubrik, lede/lead (svaret på vad/var/när/varför), brödtext, eventuell citat från VD eller nyckelspelare"},{"module_type":"text_spread","label":"Om företaget","required":true,"semantic_role":"boilerplate","description":"Standardiserad företagsbeskrivning (''Om [Företagsnamn]'') — vision, verksamhet, grundades, medarbetarantal"},{"module_type":"text_spread","label":"Mediakontakt","required":false,"semantic_role":"media_contact","description":"Namn, telefonnummer, e-postadress för journalister och media"},{"module_type":"back_cover","label":"Baksida","required":true,"description":"Baksida"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Pressmeddelande","semantic_role":"press_body","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Om företaget","semantic_role":"boilerplate","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Mediakontakt","semantic_role":"media_contact","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '1-2',
   'Professionell och nyhetsvärd — objektiv rapportering av fakta, balanserad mellan företagets perspektiv och mediasäkerhet, välformulerad lede som säger nyheterna först',
   '["Pressmeddelande-rubrik (formell etikett)","Dateline (plats och datum)","Mediakontaktuppgifter (namn, tel, e-post)"]'::jsonb);

-- process_doc
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('process_doc',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Processnamn och version-/datum-information."},{"module_type":"text_spread","label":"Syfte & scope","required":true,"semantic_role":"executive_summary","description":"Kort beskrivning av processens syfte, när den används och vilka som är inblandade."},{"module_type":"text_spread","label":"Förutsättningar & input","required":true,"semantic_role":null,"description":"Vad krävs före start — villkor, resurser, behörigheter, förberedelse."},{"module_type":"text_spread","label":"Steg-för-steg instruktioner","required":true,"semantic_role":null,"description":"Numrerade steg med ansvarig roll, tidsuppskattning och möjliga fallgropar per steg."},{"module_type":"table","label":"Roller & ansvar","required":true,"semantic_role":null,"description":"Matris som visar vem som gör vad i varje fas av processen."},{"module_type":"text_spread","label":"Felsökning & undantag","required":false,"semantic_role":null,"description":"Vanliga problem, lösningar och eskaleringsprocedur vid avvikelse från normala flödet."},{"module_type":"text_spread","label":"Output & lagring","required":false,"semantic_role":null,"description":"Vad är resultatet, var lagras det och hur länge sparas det?"},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Versionshistorik, nyckelkontakt för frågor och uppdateringsdatum."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Syfte & scope","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Förutsättningar & input","semantic_role":null,"content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Steg-för-steg instruktioner","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"table","title":"Roller & ansvar","semantic_role":null,"data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Felsökning","semantic_role":null,"content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '4-6',
   'Faktisk och instruktiv — precision och tydlighet före all annan ambition.',
   '["Version och uppdateringsdatum","Processägare / ansvarig för underhåll"]'::jsonb);

-- product_sheet
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('product_sheet',
   '[{"module_type":"cover","label":"Omslag — Produktöversikt","required":true,"description":"Produktbild/hero-grafik, produktnamn, one-liner vardeproposition"},{"module_type":"text_spread","label":"Nyckelfördelar","required":true,"semantic_role":"benefits","description":"3-4 största fördelar, bullet-listor eller kort narrativ"},{"module_type":"kpi_grid","label":"Specifikationer & Features","required":true,"semantic_role":"specs","description":"Tekniska specifikationer, storlekar, kapaciteter, kompatibilitet"},{"module_type":"text_spread","label":"Call to Action","required":true,"semantic_role":"call_to_action","description":"Hur man köper, lär sig mer, kontaktar försäljning"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Produktöversikt","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Nyckelfördelar","semantic_role":"benefits","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Specifikationer","semantic_role":"specs","data":{"kpis":[]},"stub":true},{"order":4,"module_type":"text_spread","title":"Call to Action","semantic_role":"call_to_action","content":"","data":{},"stub":true}]'::jsonb,
   '1-2',
   'Snabb, punchy, visuell. Designad för utskrift eller delning — en sida = ett intryck.',
   '[]'::jsonb);

-- project_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('project_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":"cover"},{"module_type":"text_spread","label":"Projektsammanfattning & Status","required":true,"semantic_role":"executive_summary","description":"Projekt-namn, målsättning, aktuell status (grön/gul/röd), progress % slutfört"},{"module_type":"kpi_grid","label":"Status-Indikatorer","required":true,"semantic_role":"status_metrics","description":"Budget: spenderat % av budget, kostnadskostnad, Tid: % slutfört, kritisk väg, Kvalitet: KPI"},{"module_type":"table","label":"Milstolpe-Tidslinje","required":false,"semantic_role":"milestone_timeline","description":"Milstolpe-namn, planerat slutdatum, faktiskt slutdatum, status (slutfört/i arbete/försent)"},{"module_type":"text_spread","label":"Framsteg & Prestation","required":false,"semantic_role":"achievements","description":"Senaste vecka/månad — vad är levererat, slutförda aktiviteter, milstolpar nådda"},{"module_type":"text_spread","label":"Risk-Register & Issues","required":false,"semantic_role":"risk_register","description":"Identifierade risker/problem: beskrivning, sannolikhet, påverkeffekt, ägare, mitigering"},{"module_type":"table","label":"Budget vs. Actual","required":false,"semantic_role":"budget_tracking","description":"Budgetrad, planerat, spenderat, avvikelse (%), prognos för slutkostnad"},{"module_type":"text_spread","label":"Nästa Steg & Fokus","required":false,"semantic_role":"next_steps","description":"Prioriterade aktiviteter nästa period, beroenden, resursbehov, möjliga blockerare"},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":"back_cover"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Projektsammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Status-Indikatorer","data":{"kpis":[]},"stub":true},{"order":4,"module_type":"table","title":"Milstolpe-Tidslinje","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Framsteg & Prestation","semantic_role":"achievements","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Risk & Issues","semantic_role":"risk_register","content":"","data":{},"stub":true},{"order":7,"module_type":"table","title":"Budget vs. Actual","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Nästa Steg","semantic_role":"next_steps","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '4-6',
   'Konkret, handlingsriktat lägesrapport som balanserar transparans om problem med fokus på framåtgång',
   '["Projektperiod & rapportdatum","Definition av status-färg (grön = inom plan, gul = avvikelse < 10%, röd = avvikelse > 10%)","Kritiska väg-aktiviteter","Budgetklass & kostnadsprognos-method","Projektledares kontakt & beslutsbehov"]'::jsonb);

-- proposal
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('proposal',
   '[{"module_type":"cover","label":"Omslag — Förslag","required":true,"description":"Titelblad med förslagets namn, datum, mottagare"},{"module_type":"text_spread","label":"Sammanfattning","required":true,"semantic_role":"executive_summary","description":"1-2 stycken: vad vi föreslår, värdet det skapar"},{"module_type":"text_spread","label":"Scope & Leveranser","required":true,"semantic_role":"scope","description":"Exakt vad ingår: tjänster, milstolpar, gränser"},{"module_type":"table","label":"Prissättning & Timeline","required":true,"semantic_role":"pricing_timeline","description":"Fördelat per fas, betalningsvillkor, deadline"},{"module_type":"text_spread","label":"T&C / Villkor","required":true,"semantic_role":"terms","description":"Juridiska villkor, licenser, ansvar, uppsägning"},{"module_type":"back_cover","label":"Baksida — Signering","required":true,"description":"Undertecknadsblock, kontaktuppgifter"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Förslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Scope & Leveranser","semantic_role":"scope","content":"","data":{},"stub":true},{"order":4,"module_type":"table","title":"Prissättning & Timeline","semantic_role":"pricing_timeline","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Villkor","semantic_role":"terms","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Signering","data":{},"stub":true}]'::jsonb,
   '4-6',
   'Professionell, tydlig, juridisk — varje punkt måste kunna försvaras. Fokus på claritet och transparans.',
   '["Giltighetsperiod för erbjudandet (typiskt 30 dagar)","Acceptansvillkor och signerings-krav","Eventuella risker eller antaganden"]'::jsonb);

-- quarterly
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('quarterly',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Titelomslag med period, företagslogotyp och eventuellt tema eller fokus för kvartalet."},{"module_type":"kpi_grid","label":"KPI-strip - Nyckeltal i rad","required":true,"semantic_role":null,"description":"4-6 viktigaste nyckeltal i linjär layout (omsättning, resultat, EBITDA-marginal, orderingång, kassaflöde). Snabb överblick."},{"module_type":"text_spread","label":"Highlights & kommentar","required":true,"semantic_role":null,"description":"Viktigaste affärshändelserna under perioden presenterat som bullets eller narrativ med VD-kommentar, ofta med ansiktsbild och citat."},{"module_type":"text_spread","label":"Grafsektion - Finansiell utveckling","required":true,"semantic_role":null,"description":"Diagram för omsättning, resultat, kassaflöde och orderingång över flera perioder för trend-analys. Data-driven visualisering."},{"module_type":"text_spread","label":"Tidslinje - Väsentliga händelser","required":false,"semantic_role":null,"description":"Kronologisk presentation av viktigaste händelser under perioden. Kontext för resultatförändringen."},{"module_type":"financial_summary","label":"Finansiell rapportsamling","required":true,"semantic_role":null,"description":"Resultaträkning, balansräkning, kassaflöde och nyckeltal med jämförbara perioder från tidigare år. Konsistent kolumnbredd, decimalhantering och format."},{"module_type":"text_spread","label":"Diskussion - Marknadsöversikt & Outlook","required":true,"semantic_role":"outlook","description":"Marknadsanalys, framtidsutsikter, väsentliga drivkrafter och ledningens förväntningar för kommande period."},{"module_type":"back_cover","label":"Baksida - Formella uppgifter","required":true,"semantic_role":null,"description":"Lagkrav för kvartalsrapport (MAR-disclosure, revisorsgranskning, närstående transaktioner, post-periodhändelser)."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"kpi_grid","title":"Nyckeltal","semantic_role":null,"data":{"kpis":[]},"stub":true},{"order":3,"module_type":"text_spread","title":"Highlights & kommentar","semantic_role":null,"content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Finansiell utveckling","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Väsentliga händelser","semantic_role":null,"content":"","data":{},"stub":true},{"order":6,"module_type":"financial_summary","title":"Finansiella rapporter","semantic_role":null,"data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Outlook","semantic_role":"outlook","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '8-12',
   'Investerarrapport med redaktionell tydlighet. Data-driven utan marknadsföring. Formell men tillgänglig för institutionella och privata placerare.',
   '["MAR-disclosure (Market Abuse Regulation)","Revisorsgranskning eller attestering","Närstående transaktioner","Väsentliga händelser efter periodens slut","Väsentliga redovisningsprinciper och ändringar"]'::jsonb);

-- research_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('research_report',
   '[{"module_type":"cover","label":"Omslag","required":true},{"module_type":"text_spread","label":"Sammanfattning","required":true,"semantic_role":"executive_summary","description":"Kort abstrakt av syfte, metod, huvudfynd och slutsatser."},{"module_type":"text_spread","label":"Bakgrund & frågeställning","required":true,"semantic_role":"research_question","description":"Forskningskontext, kunskapsläge och specifik frågeställning/hypotes."},{"module_type":"text_spread","label":"Metod","required":true,"semantic_role":"methodology","description":"Detaljerad beskrivning av undersökningsdesign, urval, datainsamling och analysmetoder."},{"module_type":"kpi_grid","label":"Huvudresultat & data","required":true,"semantic_role":"key_findings","description":"Centrala siffror, statistik och mätningar från studien."},{"module_type":"text_spread","label":"Slutsatser & rekommendationer","required":true,"semantic_role":"conclusions","description":"Tolkningar av resultat, begränsningar och framåtriktade implikationer."},{"module_type":"back_cover","label":"Baksida","required":true}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Bakgrund & kunskapsläge","semantic_role":"research_question","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Forskningsfrågor & hypoteser","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Metod & design","semantic_role":"methodology","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Urval & datainsamling","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Analys & tillvägagångssätt","content":"","data":{},"stub":true},{"order":8,"module_type":"kpi_grid","title":"Huvudresultat & nyckeldata","semantic_role":"key_findings","data":{"kpis":[]},"stub":true},{"order":9,"module_type":"text_spread","title":"Resultat - Del 1","content":"","data":{},"stub":true},{"order":10,"module_type":"text_spread","title":"Resultat - Del 2","content":"","data":{},"stub":true},{"order":11,"module_type":"text_spread","title":"Diskussion & tolkning","content":"","data":{},"stub":true},{"order":12,"module_type":"text_spread","title":"Slutsatser & rekommendationer","semantic_role":"conclusions","content":"","data":{},"stub":true},{"order":13,"module_type":"text_spread","title":"Begränsningar & framtida forskning","content":"","data":{},"stub":true},{"order":14,"module_type":"text_spread","title":"Referenser","semantic_role":"bibliography","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '12-20',
   'Strikt vetenskaplig, transparens om metod, återhållen slutsatsdragning — följer forskningsetik och rigor.',
   '["Etiska godkännanden och samtycke (om tillämpligt)","Intressekonflikter och finansiering av forskningen","Metodologiska begränsningar och validitet","Antaganden och osäkerhet i resultaten","Begränsningar i generaliserbarhet"]'::jsonb);

-- sales_proposal
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('sales_proposal',
   '[{"module_type":"cover","label":"Omslag — Försäljningserbjudande","required":true,"description":"Titelblad med produktnamn/varumärke, giltighetsperiod"},{"module_type":"text_spread","label":"Erbjudandet","required":true,"semantic_role":"offer","description":"Produktbeskrivning, nyckelfördelar, varför just nu"},{"module_type":"table","label":"Prisstruktur & Paket","required":true,"semantic_role":"pricing_table","description":"Paketoptioner, pris per nivå, rabatter, betalningsmöjligheter"},{"module_type":"text_spread","label":"Implementering & Support","required":false,"semantic_role":"delivery_terms","description":"Onboarding, support-nivåer, SLA, training"},{"module_type":"text_spread","label":"Nästa Steg","required":true,"semantic_role":"call_to_action","description":"Hur man accepterar, signering, kontakt för frågor, deadline"},{"module_type":"back_cover","label":"Baksida","required":true,"description":"Företagsinfo, juridisk text, kontaktuppgifter"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Försäljningserbjudande","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Erbjudandet","semantic_role":"offer","content":"","data":{},"stub":true},{"order":3,"module_type":"table","title":"Prissättning","semantic_role":"pricing_table","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Implementering & Support","semantic_role":"delivery_terms","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Nästa Steg","semantic_role":"call_to_action","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '4-6',
   'Försäljnings-orienterad, invitande, resultat-fokuserad. Tydliga call-to-actions, minimal juridisk text.',
   '["Giltighetsperiod (denna erbjudandet är giltigt fram till...)","Betalningsvillkor (på faktura, förskott etc)","Standardvillkor för tjänster eller produkter"]'::jsonb);

-- strategy_doc
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('strategy_doc',
   '[{"module_type":"cover","label":"Omslag","required":true},{"module_type":"text_spread","label":"Vision & mål","required":true,"semantic_role":"vision_mission","description":"Långsiktig vision och konkreta mål för strategiperioden."},{"module_type":"text_spread","label":"Nuläge & utmaningar","required":true,"semantic_role":"current_state_analysis","description":"Analys av utgångspunkt, styrkor, svagheter och externa trender."},{"module_type":"text_spread","label":"Strategiska initiativ","required":true,"semantic_role":"strategic_initiatives","description":"Huvudsakliga satsningar och åtgärder för att nå målen."},{"module_type":"text_spread","label":"Vägkarta & tidplan","required":true,"semantic_role":"roadmap_timeline","description":"Tidsplan för genomförande, milstolpar och prioritering över perioden."},{"module_type":"text_spread","label":"KPI:er & uppföljning","required":true,"semantic_role":"kpis_governance","description":"Nyckeltal för att mäta framgång och styrning av genomförandet."},{"module_type":"back_cover","label":"Baksida","required":true}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Nuläge & kontext","semantic_role":"current_state_analysis","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Vision för 2026-2028","semantic_role":"vision_mission","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Strategiska prioriteringar","semantic_role":"strategic_initiatives","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Initiativ 1: [Namn]","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Initiativ 2: [Namn]","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Initiativ 3: [Namn]","content":"","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Vägkarta & tidplan","semantic_role":"roadmap_timeline","content":"","data":{},"stub":true},{"order":9,"module_type":"kpi_grid","title":"Framgångskriterer & KPI:er","semantic_role":"kpis_governance","data":{"kpis":[]},"stub":true},{"order":10,"module_type":"text_spread","title":"Risker & beroenden","content":"","data":{},"stub":true},{"order":11,"module_type":"text_spread","title":"Genomförande & styrning","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '8-12',
   'Övertygande, handlingsorienterad, fokuserad — Internt dokument för alignment, ej för extern publicering.',
   '["Antaganden om marknad, resurser och externa faktorer","Beroenden på andra funktioner eller externa partners","Risker och mitigering av nyckelrisker","Förväntade investeringar och ROI (om relevant)"]'::jsonb);

-- sustainability_report
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('sustainability_report',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":"cover"},{"module_type":"text_spread","label":"VD-ord / Hållbarhetsinledning","required":true,"semantic_role":"executive_summary","description":"Ledningens perspektiv på hållbarhetsarbetet, åtaganden och framåtsyftande vision"},{"module_type":"kpi_grid","label":"Hållbarhetsnyckeltal","required":true,"semantic_role":"sustainability_metrics","description":"Scope 1, 2, 3 utsläpp, energi, vatten, avfall, jämförelsetal årets ökning/minskning"},{"module_type":"table","label":"GRI/CSRD Ramverk & Matris","required":false,"semantic_role":"materiality_matrix","description":"Väsentlighetsanalys — prioriterade område, påverkeffekt, stakeholder-relevans"},{"module_type":"text_spread","label":"Social påverkan & Arbetsvillkor","required":false,"semantic_role":"social_impact","description":"Mångfald, inkludering, löne- och arbetsmiljöinitiativ, mänskliga rättigheter"},{"module_type":"text_spread","label":"Miljöinitiativ & Biodiversitet","required":false,"semantic_role":"environmental_action","description":"Klimatåtgärder, kemikaliehantering, cirkuläritet, naturmål"},{"module_type":"text_spread","label":"Styrning & Etik","required":false,"semantic_role":"governance","description":"Styrningsstruktur, etikkod, korruptionsbekämpning, whist­blower-system"},{"module_type":"table","label":"Måluppfyllelse & Progress","required":false,"semantic_role":"target_tracking","description":"2030-mål, aktuell progress, procentandel slutförande, riskanalys för måluppfyllelse"},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":"back_cover"}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"VD-ord","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"kpi_grid","title":"Hållbarhetsnyckeltal","data":{"kpis":[]},"stub":true},{"order":4,"module_type":"table","title":"Väsentlighetsanalys","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Miljöinitiativ","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Social påverkan","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Styrning & Etik","content":"","data":{},"stub":true},{"order":8,"module_type":"table","title":"Måluppfyllelse 2030","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '20-40',
   'Ansvarig, faktabaserad transparens med visioner om positiv påverkan och systemisk förändring',
   '["GRI & CSRD-referens — vilka standarder följs","Scope-definition för växthusgaser (Scope 1/2/3)","Väsentlighetsanalys & stakeholder-dialog","Revisorskommentar på hållbarhetsdata (frivillig tredjepartsverifiering)","3-års historik för KPI-jämförelse"]'::jsonb);

-- training_material
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('training_material',
   '[{"module_type":"cover","label":"Omslag","required":true,"semantic_role":null,"description":"Kursnamn, målgrupp och kursens datum/version."},{"module_type":"text_spread","label":"Kursmål & struktur","required":true,"semantic_role":"executive_summary","description":"Vad ska deltagaren kunna efter kursen? Förväntad tidsåtgång och modulöversikt."},{"module_type":"text_spread","label":"Modul 1 — Introduktion & bakgrund","required":true,"semantic_role":null,"description":"Grundläggande koncept, kontext och varför detta är viktigt."},{"module_type":"text_spread","label":"Modul 2 — Kärninnehål","required":true,"semantic_role":null,"description":"Huvudsakligt lärande, steg-för-steg exempel och praktiska övningar."},{"module_type":"text_spread","label":"Modul 3 — Tillämpning & fallstudier","required":true,"semantic_role":null,"description":"Verkliga exempel, case studies och hur innehållet tillämpas i praktiken."},{"module_type":"text_spread","label":"Sammanfattning & nästa steg","required":true,"semantic_role":null,"description":"Kort repetition, bedömning (quiz eller övningar) och rekommenderad vidare läsning."},{"module_type":"table","label":"Övningsuppgifter & bedömning","required":false,"semantic_role":null,"description":"Fristående övningar med lösningar, svarsnyckel eller feedback-mekanismer."},{"module_type":"back_cover","label":"Baksida","required":true,"semantic_role":null,"description":"Resurser, glossarium och kontakt för frågor."}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","semantic_role":null,"data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Kursmål & struktur","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Modul 1 — Introduktion & bakgrund","semantic_role":null,"content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Modul 2 — Kärninnehål","semantic_role":null,"content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Modul 3 — Tillämpning & fallstudier","semantic_role":null,"content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Sammanfattning & bedömning","semantic_role":null,"content":"","data":{},"stub":true},{"order":7,"module_type":"table","title":"Övningsuppgifter med lösningar","semantic_role":null,"data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","semantic_role":null,"data":{},"stub":true}]'::jsonb,
   '12-20',
   'Engagerande och lätt att följa — progressiva exempel från enkelt till komplext.',
   '["Lärandemål","Förväntad tidsåtgång","Förutsättningar (förkunskaper)"]'::jsonb);

-- white_paper
INSERT INTO document_type_templates (document_type, required_sections, default_stub_plan, recommended_pages, tone_hints, disclosures) VALUES
  ('white_paper',
   '[{"module_type":"cover","label":"Omslag","required":true},{"module_type":"text_spread","label":"Sammanfattning","required":true,"semantic_role":"executive_summary","description":"Prägnant överblick av problemet, metoden och huvudfynden."},{"module_type":"text_spread","label":"Problembeskrivning","required":true,"semantic_role":"problem_framing","description":"Kontextualisering av området, relevans och motivering för studien."},{"module_type":"text_spread","label":"Slutsatser & rekommendationer","required":true,"semantic_role":"conclusions","description":"Huvudsakliga fynd, insikter och framåtriktade rekommendationer."},{"module_type":"back_cover","label":"Baksida","required":true}]'::jsonb,
   '[{"order":1,"module_type":"cover","title":"Omslag","data":{},"stub":true},{"order":2,"module_type":"text_spread","title":"Sammanfattning","semantic_role":"executive_summary","content":"","data":{},"stub":true},{"order":3,"module_type":"text_spread","title":"Problemställning","semantic_role":"problem_framing","content":"","data":{},"stub":true},{"order":4,"module_type":"text_spread","title":"Kapitel 1: Bakgrund & kontext","content":"","data":{},"stub":true},{"order":5,"module_type":"text_spread","title":"Kapitel 2: Huvudanalys","content":"","data":{},"stub":true},{"order":6,"module_type":"text_spread","title":"Kapitel 3: Implikationer & framtid","content":"","data":{},"stub":true},{"order":7,"module_type":"text_spread","title":"Slutsatser & rekommendationer","semantic_role":"conclusions","content":"","data":{},"stub":true},{"order":8,"module_type":"text_spread","title":"Referenser","semantic_role":"bibliography","content":"","data":{},"stub":true},{"order":99,"module_type":"back_cover","title":"Baksida","data":{},"stub":true}]'::jsonb,
   '12-20',
   'Auktoritativ, evidensbaserad, genomtänkt — balanserar akademisk rigor med läsbar narrativ.',
   '["Metodologiska begränsningar och antaganden","Definitioner av nyckelbegrepp","Disclaimer om att detta inte utgör juridisk eller investeringsrådgivning (om relevant)"]'::jsonb);
