import { randomUUID } from "node:crypto";
import { connectLambda, getStore } from "@netlify/blobs";
import { z } from "zod";
import { json, noContent } from "./cors.js";
import { requireHubAuth } from "./auth-middleware.js";
import { getSql } from "./db.js";

const assetType = z.enum(["design_example", "photo", "logo", "pdf_reference"]);

const createSchema = z
  .object({
    document_id: z.string().uuid().optional(),
    brand_profile_id: z.string().uuid().optional(),
    asset_type: assetType,
    mime_type: z.string().min(1),
    filename: z.string().min(1),
    blob_key: z.string().min(1).optional(),
    file_base64: z.string().min(1).optional(),
    metadata: z.record(z.any()).optional(),
  })
  .refine((value) => Boolean(value.blob_key || value.file_base64), {
    message: "Either blob_key or file_base64 is required",
  });

const patchSchema = z.object({
  metadata: z.record(z.any()).optional(),
  document_id: z.string().uuid().nullable().optional(),
  brand_profile_id: z.string().uuid().nullable().optional(),
});

function parseBody(event) {
  try {
    return event.body ? JSON.parse(event.body) : {};
  } catch {
    return null;
  }
}

function dataUrlToBuffer(maybeDataUrl) {
  const clean = maybeDataUrl.includes(",") ? maybeDataUrl.split(",").pop() : maybeDataUrl;
  return Buffer.from(clean || "", "base64");
}

function createStore(event) {
  try {
    connectLambda(event);
    return getStore("report-ai-assets");
  } catch {
    const siteID = process.env.NETLIFY_SITE_ID;
    const token = process.env.NETLIFY_API_TOKEN;
    if (!siteID || !token) return null;
    return getStore({ name: "report-ai-assets", siteID, token });
  }
}

function buildBlobUrl(key) {
  const baseUrl = process.env.ASSET_BLOB_BASE_URL || process.env.FONT_BLOB_BASE_URL;
  if (!baseUrl) return key;
  return `${baseUrl.replace(/\/$/, "")}/${key}`;
}

function getIdAndActionFromPath(path = "") {
  const clean = path.split("?")[0];
  const parts = clean.split("/").filter(Boolean);
  const idx = parts.lastIndexOf("design-assets");
  if (idx === -1) return { id: null, action: null };
  return {
    id: parts[idx + 1] ?? null,
    action: parts[idx + 2] ?? null,
  };
}

async function maybeCreatePhotoDerivatives(sql, assetId, blobKey) {
  const variants = ["thumb", "preview", "print"];
  for (const variant of variants) {
    await sql`
      INSERT INTO asset_derivatives (id, asset_id, variant, blob_key, metadata)
      VALUES (${randomUUID()}, ${assetId}, ${variant}, ${blobKey}, ${JSON.stringify({ autogenerated: true })}::jsonb)
      ON CONFLICT (asset_id, variant) DO NOTHING
    `;
  }
}

async function getAssetById(sql, id, hubUserId) {
  const rows = await sql`
    SELECT *
    FROM design_assets
    WHERE id = ${id} AND hub_user_id = ${hubUserId} AND deleted_at IS NULL
    LIMIT 1
  `;
  return rows[0] ?? null;
}

export const handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return noContent(event);

  const auth = requireHubAuth(event);
  if (!auth.ok) return json(event, auth.status, { error: auth.error });

  const sql = getSql();
  const { id, action } = getIdAndActionFromPath(event.path);

  if (event.httpMethod === "GET") {
    const query = event.queryStringParameters || {};
    const rows = await sql`
      SELECT *
      FROM design_assets
      WHERE
        hub_user_id = ${auth.hubUserId}
        AND deleted_at IS NULL
        AND (${query.document_id ?? null}::uuid IS NULL OR document_id = ${query.document_id ?? null}::uuid)
        AND (${query.brand_profile_id ?? null}::uuid IS NULL OR brand_profile_id = ${query.brand_profile_id ?? null}::uuid)
        AND (${query.asset_type ?? null}::text IS NULL OR asset_type = ${query.asset_type ?? null}::text)
      ORDER BY created_at DESC
    `;

    return json(event, 200, { items: rows });
  }

  if (event.httpMethod === "POST" && !id) {
    const body = parseBody(event);
    if (!body) return json(event, 400, { error: "Invalid JSON" });

    const parsed = createSchema.safeParse(body);
    if (!parsed.success) return json(event, 400, { error: "Invalid payload", issues: parsed.error.issues });

    let blobKey = parsed.data.blob_key;
    if (!blobKey && parsed.data.file_base64) {
      const store = createStore(event);
      if (!store) {
        return json(event, 500, {
          error: "Blob store not configured",
          details: "Set Netlify Blobs context or NETLIFY_SITE_ID + NETLIFY_API_TOKEN",
        });
      }

      const ext = parsed.data.filename.includes(".") ? parsed.data.filename.split(".").pop() : "bin";
      const key = `${auth.hubUserId}/${randomUUID()}.${ext}`;
      const bytes = dataUrlToBuffer(parsed.data.file_base64);
      await store.set(key, bytes, {
        contentType: parsed.data.mime_type,
        metadata: {
          filename: parsed.data.filename,
          asset_type: parsed.data.asset_type,
        },
      });
      blobKey = buildBlobUrl(key);
    }

    const assetId = randomUUID();
    const metadata = {
      ...(parsed.data.metadata || {}),
      source: parsed.data.file_base64 ? "upload_base64" : "external_blob_key",
      uploaded_at: new Date().toISOString(),
    };

    const rows = await sql`
      INSERT INTO design_assets (
        id,
        hub_user_id,
        document_id,
        brand_profile_id,
        asset_type,
        mime_type,
        filename,
        blob_key,
        metadata
      ) VALUES (
        ${assetId},
        ${auth.hubUserId},
        ${parsed.data.document_id ?? null}::uuid,
        ${parsed.data.brand_profile_id ?? null}::uuid,
        ${parsed.data.asset_type},
        ${parsed.data.mime_type},
        ${parsed.data.filename},
        ${blobKey},
        ${JSON.stringify(metadata)}::jsonb
      )
      RETURNING *
    `;

    if (parsed.data.asset_type === "photo") {
      await maybeCreatePhotoDerivatives(sql, assetId, blobKey);
    }

    return json(event, 201, { item: rows[0] });
  }

  if (event.httpMethod === "POST" && id && action === "analyze") {
    const asset = await getAssetById(sql, id, auth.hubUserId);
    if (!asset) return json(event, 404, { error: "Asset not found" });

    const isPdf = asset.mime_type.toLowerCase().includes("pdf");
    const isImage = asset.mime_type.toLowerCase().startsWith("image/");

    const analysis = {
      analyzed_at: new Date().toISOString(),
      is_pdf: isPdf,
      is_image: isImage,
      layout_hint: isPdf ? "multi_page_reference" : "single_surface_reference",
      focus_recommendation: asset.asset_type === "photo" ? "Set focal point before layout" : null,
      design_signal: {
        typography: "inferred",
        spacing: "inferred",
        color_palette: "inferred",
      },
    };

    const updated = await sql`
      UPDATE design_assets
      SET metadata = COALESCE(metadata, '{}'::jsonb) || ${JSON.stringify({ analysis })}::jsonb
      WHERE id = ${id} AND hub_user_id = ${auth.hubUserId} AND deleted_at IS NULL
      RETURNING *
    `;

    return json(event, 200, { item: updated[0] });
  }

  if (event.httpMethod === "PATCH" && id) {
    const body = parseBody(event);
    if (!body) return json(event, 400, { error: "Invalid JSON" });

    const parsed = patchSchema.safeParse(body);
    if (!parsed.success) return json(event, 400, { error: "Invalid payload", issues: parsed.error.issues });

    const asset = await getAssetById(sql, id, auth.hubUserId);
    if (!asset) return json(event, 404, { error: "Asset not found" });

    const mergedMetadata = {
      ...(asset.metadata || {}),
      ...(parsed.data.metadata || {}),
      updated_at: new Date().toISOString(),
    };

    const rows = await sql`
      UPDATE design_assets
      SET
        document_id = COALESCE(${parsed.data.document_id ?? null}::uuid, document_id),
        brand_profile_id = COALESCE(${parsed.data.brand_profile_id ?? null}::uuid, brand_profile_id),
        metadata = ${JSON.stringify(mergedMetadata)}::jsonb
      WHERE id = ${id} AND hub_user_id = ${auth.hubUserId} AND deleted_at IS NULL
      RETURNING *
    `;

    return json(event, 200, { item: rows[0] });
  }

  if (event.httpMethod === "DELETE" && id) {
    const rows = await sql`
      UPDATE design_assets
      SET deleted_at = NOW()
      WHERE id = ${id} AND hub_user_id = ${auth.hubUserId} AND deleted_at IS NULL
      RETURNING id
    `;
    if (!rows[0]) return json(event, 404, { error: "Asset not found" });
    return noContent(event);
  }

  return json(event, 405, { error: "Method Not Allowed" });
};
